### ISSUE TITLE
Error 500 al reiniciar - configuracion no persiste

### ISSUE THREAD

**Issue by gvarela1981** [datosgobar/portal-andino#291]
Primero quería felicitarlos por las mejoras que le introdujeron al ckan, tener la imagen en dockerhub y no recompilar con cada reinicio es un avance importante.

En el archivo de ejemplo latest.yml no se persiste la configuración del portal, por eso al reiniciar el stack no se puede acceder a andino. Para solucionar ese problema es necesario volver a correr el script de configuración cada vez que se inicia
``` 
docker-compose -f latest.yml exec portal /etc/ckan_init.d/init.sh -e "$EMAIL" -h "$HOST" \
        -p "$DB_USER" -P "$DB_PASS" \
        -d "$STORE_USER" -D "$STORE_PASS" 
```
Estoy teniendo problemas para persistir la información de configuración, si bien el archivo de configuracion se actualiza con la configurción de los puertos y los usuarios de la DB, no los toma el andino.

Esta es la modificacion que le hice al latest.yml para persistir la configuracion, montar la ruta :/etc/ckan/default/  al disco local en .data/
```
  portal:
    container_name: andino
    image: "datosgobar/portal-andino:${ANDINO_TAG}"
    restart: always
    ports:
      - "${DATASTORE_HOST_PORT}:8800"
    depends_on:
      - solr
      - redis
      - postfix
    networks:
      - portal-network
    environment:
      - TZ
    volumes:
      - postfix_log:/var/log/shared/postfix
      - .data/:/etc/ckan/default/
```
Tampoco pude hacer persistir la configuracion con esta segunda modificacion al latest.yml montando en volumenes lógicos de docker las rutas etc/ckan, /usr/lib/ckan y /var/lib/ckan tomando el ejemplo del stack de ckan

```
  portal:
    container_name: andino
    image: "datosgobar/portal-andino:${ANDINO_TAG}"
    restart: always
    ports:
      - "${DATASTORE_HOST_PORT}:8800"
    depends_on:
      - solr
      - redis
      - postfix
    networks:
      - portal-network
    environment:
      - TZ
    volumes:
      - ckan_config:/etc/ckan
      - ckan_home:/usr/lib/ckan
      - ckan_storage:/var/lib/ckan
volumes:
  ckan_config:
  ckan_home:
  ckan_storage:
  pg_data:
  solr_data:
```

El error que arroja es
```
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
```
Si pudieran indicarme que mas falta persistir para el portal se comunique con la DB y no se interrumpa con la aparicion de un error.

Muchas gracias
